version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment: 
      - APP_NAME=MyFlaskApp
      - FLASK_APP=run.py
      - FLASK_ENV=development
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "3000:80"